### ISSUE TITLE
run_vectree_quantize_mc.sh costs more than 48G

### ISSUE THREAD

**Issue by ArSpi** [DekuLiuTesla/CityGaussian#26]
I run `bash run_vectree_quantize_mc.sh` with A40 48G, and encounter `torch.cuda.OutOfMemoryError: CUDA out of memory`. What's wrong? As far as I know, the author use A100 40G.

**Comment by ArSpi** [comment]
This problem has been solved. In the script `run_vectree_quantize_mc.sh`, there is `CUDA_VISIBLE_DEVICES=0` instead of `CUDA_VISIBLE_DEVICES=$gpu_id`. Sorry about my overlook.
