### ISSUE TITLE
how to fix V1 cuda error 

### ISSUE THREAD

**Issue by zzz5y** [DekuLiuTesla/CityGaussian#69]
Hello!I try to train the MatrixCity street-view data on CityGaussianV1!
after preparing the data like aerial data,I try to finish the first train_large.py 
And In the first iteration,it seems some problem in rasterizer part
`
rendered_image, radii = rasterizer(
        means3D = means3D,
        means2D = means2D,
        shs = shs,
        colors_precomp = colors_precomp,
        opacities = opacity,
        scales = scales,
        rotations = rotations,
        cov3D_precomp = cov3D_precomp)
    # Those Gaussians that were frustum culled or had a radius of 0 were not visible.
    # They will be excluded from value updates used in the splitting criteria.
    return {"render": rendered_image,
            "viewspace_points": screenspace_points,
            "visibility_filter" : radii > 0,
            "radii": radii}
`
the output image tensor is on cpu, so I can't calculate L1_loss with gt_image
but i try to move the output image tensor to my gpu where the gt_image in,But the error happen,the error was common in diff-gaussian-rasterization
Any advice?
the error looks like
`
Training progress:   0%|                              | 0/30000 [00:00<?, ?it/s]
image device: cpu, shape: torch.Size([3, 250, 250]) [10/12 16:57:24]
gt_image device: cuda:0, shape: torch.Size([3, 250, 250]) [10/12 16:57:24]
Allocated memory: 1291854848 bytes [10/12 16:57:24]
Reserved memory: 1369440256 bytes [10/12 16:57:24]
Traceback (most recent call last):
  File "/media/ry/rayan/CityGaussian/train_large.py", line 330, in <module>
    training(lp, op, pp, args.test_iterations, args.save_iterations, args.refilter_iterations, args.checkpoint_iterations, args.start_checkpoint, args.max_cache_num, args.debug_from)
  File "/media/ry/rayan/CityGaussian/train_large.py", line 119, in training
    image = image.to(device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Training progress:   0%|                              | 0/30000 [00:00<?, ?it/s]

`

**Comment by zzz5y** [comment]
![image](https://github.com/user-attachments/assets/8b06e438-343f-46fc-9969-db69a7a60970)
the error pic here,maybe better to check!Thank you!

**Comment by zzz5y** [comment]
I soled it,Because there are some params input to rasterizer on cpu.It leads to the image output's device on cpu.

**Comment by kaikai23** [comment]
Hi @zzz5y, what params turned out to be on cpu in you case? I met the same problem but don't think I've changed any code.
I am using multiple GPUs for finetuning 36 blocks in MatrixCity-SmallCity, and this error happens occasionally, like 1 out of 5 gpus.

**Comment by zzz5y** [comment]
> Hi @zzz5y, what params turned out to be on cpu in you case? I met the same problem but don't think I've changed any code.
> I am using multiple GPUs for finetuning 36 blocks in MatrixCity-SmallCity, and this error happens occasionally, like 1 out of 5 gpus.

Hello，@kaikai23 
I use only one GPU to train.
I think the problem is the tensor which you input to rasterizer on cpu.
So i think you can debug by printf all the tensors’ devices.
In my case， i remember is the means3D on cpu，But it’s better to check all the params in the below part![IMG_20241215_132154.jpg](https://github.com/user-attachments/assets/93edae60-f923-46fd-966a-11560c7d993b)

**Comment by kaikai23** [comment]
@zzz5y thanks! It is weird that when I debug, everything works fine. And actually many out of the 36 cells can successfully complete training and save a point_cloud.ply. But the `CUDA error: an illegal memory access was encountered` happens for some cells.

Anyway, I can get around this problem by rerunning the failed cells, and they can be constructed. Not sure what caused that.
